### PR TITLE
Drop style pseudo elements

### PR DESCRIPTION
**Pull request by bfintal**
This is for issue #58

### CODE REVIEW

**Comment by anthonyjb** [comment]
I'm going to have a play with this over the weekend and also look at creating a SVG version of the background images instead of the current PNGs (that allows for more control in styling them).

Not sure why the merge is failing to pass the travis-ci test - I sometimes get failures and have to just re-run the test on travis-ci to make it work but it's not working in this case. Could you do me a favour and run the PR through on your machine with `grunt jasmine` and opening the `SpecRunner.html` in a browser - let me know if you see any error.

**Comment by bfintal** [comment]
I'm getting these:

```
   ContentTools.ToolboxUI > Keyboard short-cuts
     - should allow a non-content element to be removed with the delete key shor
     ✓ should allow a non-content element to be removed with the delete key short-cut
     X should allow a undo to be triggered with Ctrl-z key short-cut
       Expected 1 to be 2. (1)
     X should allow a redo to be triggered with Ctrl-Shift-z key short-cut
       Expected 2 to be 1. (1)```

Weird that I didn't have any changes except for the css

**Comment by anthonyjb** [comment]
Thanks - the issue is to do with keyboard events and clearly has nothing to do with your chnage - why you get that error and I don't I have no idea, especially considering travis-ci is passing for me and not for your pull request - no matter - one way or the other I'll get this pull request in and passing the tests.

**Comment by bfintal** [comment]
Weird anomaly, I've added `!important` to z-index and the jasmine error magically went away.

**Comment by anthonyjb** [comment]
I'm having issues with timed tests not always passing on travis-ci (though the issue is with my test spec) - I suspect this might be the culprit - it can't be a CSS change causing the issue surely?

**Comment by bfintal** [comment]
I doubt it the original error I encountered was in js `ContentTools.ToolboxUI` this definitely isn't affected by CSS.

**Comment by anthonyjb** [comment]
I've now had time to test this on my machine and it's a big improvement :+1:  The change actually needs making in the ContentEdit repo, and then ContentTools will need the dependency updating. 

I'm happy to make the change to ContentEdit or accept a pull request there - I still want to try to get SVG images in place for the camera icon and arrows so don't mind making the change at that point.

Thanks again for this it's a really nice improvement :)

**Pull request closed without merging**
