### PR TITLE
experimental support for multi class styles

### PR DESCRIPTION
**Pull request by tvaliasek**
Allows using multiple classes in ContentTools.Style. Sorry for my low JS skills.

Example:
```javascript
       ContentTools.StylePalette.add([
            new ContentTools.Style('Warning', 'alert alert-warning', ['p','div']),
            new ContentTools.Style('Button', 'btn btn-primary', ['a'])
        ]);
```

### CODE REVIEW

**Comment by anthonyjb** [comment]
Hi @tvaliasek thanks for the suggestion. Any changes would have to be submitted as changes to the CoffeeScript not the JavaScript as the JavaScript is built using grunt from the CoffeeScript. I only leave compiled JavaScript in place for builds and external dependencies (as in this case content-edit.js is a dependancy for ContentTools so the changes would need to be made to the CoffeeScript in that repo https://github.com/GetmeUK/ContentEdit and the dependancy updated in this one - I'm sorry if that seems very convoluted).

Using CoffeeScript the function parameters might be changed like so to use splats:

    addCSSClasses: (domElement, classNames...) ->
        ...

Allowing the function to be called like so:

    ContentEdit.addCSSClasses(myElement, 'alert', 'alert-warning');

Which I agree would potentially be an improvement, however really it seems like what you'd really like is to be able to set multiple classes when defining a style, perhaps in the form:

    new ContentTools.Style('Warning', ['alert', 'alert-warning'], ['p','div']),

You'll note that in the sandbox demo included in the repo there is a set of classes for setting good and bad example styles. Here I have to use 3 styles; *Example, Good example, Bad example*. On this basis I agree with you that support for multiple classes would be an improvement, it requires less options to be shown to the user and also prevents the issue where the user doesn't realise they need to select both *Example* and *Good example*.

I don't believe your suggested solution will solve this problem *fully* however as whilst multiple classes will be applied the editor wont correctly check that both classes are applied to the current element and therefore the switch wont update correctly (at least I believe that's the case).

I think the changes actually need to be made in the ContentTools library to the following sections:

- https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/styles.coffee#L31
- https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/inspector.coffee#L143
- https://github.com/GetmeUK/ContentTools/blob/master/src/scripts/ui/dialogs/properties.coffee#L57

This is definitely a feature I'd like to add/see moving forward.

**Comment by tvaliasek** [comment]
Thank you for feedback, my JS knowledge is poor, so I meant it only as suggestion of functionality. I will try to rewrite this in coffeescript, just for myself. I also take a look into sandbox. 

Odesláno ze smartphonu Sony Xperia™

Anthony Blackshaw <notifications@github.com>napsal/a:

**Comment by tvaliasek** [comment]
Btw. I think, the switch is updated somehow correctly, I have spent half a day on trying to achieve it. :)

Odesláno ze smartphonu Sony Xperia™

Anthony Blackshaw <notifications@github.com>napsal/a:

**Comment by anthonyjb** [comment]
@tvaliasek  If you get it working in CoffeeScript please submit it back as I'll be making this feature part of the first development milestone for sure :)

**Comment by btbjosh** [comment]
Any update on this feature? I'd like to use this within ui frameworks and it makes the most sense to apply multiple css style classes at once like `ui button green` etc

**Comment by anthonyjb** [comment]
Hi @btbjosh - I think I closed the issue due to lack of activity. The initially approach taken by to solving this had a number of issues and a new approach would have been required.

If you want create a new issue for this I'll happily flag it as an enhancement and either work on myself when I get chance or open it up for others to contribute to?

**Comment by btbjosh** [comment]
Thanks for the follow-up. We ended up needing a different type of editor. Although I would love to use ContentTools in the future. Great job!

**Pull request closed without merging**
