### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mimoduo**
Update format of all sass to use 2 space indentation and idiomatic css.

### CODE REVIEW

**Comment by anthonyjb** [comment]
Hi @mimoduo my preference is to use 4 spaces consistently in both SASS and CoffeeScript, I understand people have different preferences but for the main project repo I'm going to be sticking with 4.

**Comment by mimoduo** [comment]
Hey @anthonyjb you're quick! That makes sense. Anything I could do on the SASS end of things?

**Comment by anthonyjb** [comment]
Hi @mimoduo - caught me at the right time :)

With regard to SASS I don't see the interface for the desktop version of the browser changing much in right now - the next major change will be adding support for smaller screen and touch devices as there's been quite a few requests for mobile/tablet support. Whilst mobile support is a fair way off on my list of things still to do if someone wanted to look at UI/UX for the interface on such devices that would be a real help - I'm quite to make the modifications to the JavaScript to support touch in the sort term.

Not sure how much your in to UI/UX design but even if your not clearly your SASS stuff is very neat so if you were able to lend your skills to a responsive version of the UI that would be awesome.

**Comment by mimoduo** [comment]
Hi @anthonyjb - awesome!

Sounds good. 

Which method would you prefer for beginning a responsive version? My preference is min-width and having media queries directly within the selector. However, i'm open to anything! From a design standpoint we could see how well a condensed version works first yea?

**Comment by anthonyjb** [comment]
This is the SASS I use to build responsive mixins on the getcontenttools.com website, I think it works well but this isn't my area of expertise to be honest so other recommendations are very welcome:

    /* Responsive breakpoints */
    $tablet-width: 768px;
    $desktop-width: 1024px;

    /*
    These mixins make it easy to define blocks of CSS for the target devices, for
    example:

        @include media-tablet {
            ...tablet CSS here...
        }

    As a general rule the base CSS should target mobiles and conditional blocks
    should be added for tablet and desktop devices. Don't apply this rule over
    smaller more manageable code.
    */
    @mixin media-mobile {
        @media (max-width: #{$tablet-width - 1}) {
            @content;
        }
    }

    @mixin media-tablet {
        @media (min-width: #{$tablet-width}) {
            @content;
        }
    }

    @mixin media-desktop {
        @media (min-width: #{$desktop-width}) {
            @content;
        }
    }

With regard to design this is the really tricky bit, it wouldn't be to much work to make the editor *work* in a touch environment but making the UX great is a whole other matter and kind of why it didn't make it to the first release.

I was thinking on tablet we might look at docking the toobox top for portrait, right for landscape, with regard to mobile I think we might need to go on the basis that the toolbox is hidden until you select some kind of button to show it, select a tool at which point it's hidden again (but that doesn't sound ideal either).

Other considerations are what to do with the current dialogs, these are probably fine for tablet as is but for mobile maybe a fullscreen dialog that scrolls would work better?

What are your thoughts? Perhaps I should add an issue for responsive/touch support and open the discussion up?

**Pull request closed without merging**
