### PR TITLE
Added traditional chinese json under filename tw.json

### PR DESCRIPTION
**Pull request by robinlluu2002**
Added traditional chinese json under filename tw.json. In addition, I changed one line
in cn.json as I think it was not correctly translated.

### CODE REVIEW

**Comment by robinlluu2002** [comment]
please feel free to discuss with me

**Comment by anthonyjb** [comment]
Hi @robinlluu2002 thank you for the translations. Looks like we may have a problem with the naming of both the `cn.json` file and the `tw.json`. According to the [ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) Chinese should be named `zh.json` and I can't find a code for Traditional Chinese. According to the list `tw` represents Niger–Congo and `cn` doesn't have a value in the list (I should have checked that when the first translations was provided).

Would be great to merge these translations in but could you advise on what to name Traditional Chinese? (I can rename existing cn translation file after.) Possibly the files would become `zh.json` and `zh-traditional.json`?

**Comment by robinlluu2002** [comment]
Hi @anthonyjb, from my understanding.  Simplified Chinese(China) could be named **zh-cn.json** and traditional Chinese(Taiwan) be named **zh-tw.json**. This naming convention is commonly used in dealing with simplified and traditional Chinese.

**Comment by anthonyjb** [comment]
That makes sense (like en-us, en-gb), I'll merge your changes in and rename the files thanks :+1:

**Pull request merged**
